### PR TITLE
DTS more close to stock (fixes reversed volume buttons)

### PR DESCRIPTION
**Pull request by vladimiroltean**
* The watchdog configuration and the regulator voltages, we have no reason to change from stock.
* The volume keys mapping bug was reported here: https://forum.xda-developers.com/showpost.php?p=77147619&postcount=1812. Looks like we missed the DTS configuration that was applied in stock.

Sent as a single pull request because I didn't want to deal with merge conflicts if these were to be merged separately.

### CODE REVIEW

**Comment by Gabriel85** [comment]
I did all three things intentionally!
1. the watchdog bark time is irrelevant, since we don't have a watchdog
2. no overclocking! the stock setting is crazy, makes no sense, wastes power, outside specification and nobody has complained about it.. And we already talked about that. Just some leftover debug bullshit.
3. the volume keys are indeed switched, but not because of that setting. That makes no sense, since if this would be true, they wouldn't be switched, they would be identical... Maybe because of the new rotation method? You need to switch them in the key-layout file.

**Comment by vladimiroltean** [comment]
> we don't have a watchdog

Can you tell me more?

> the volume keys are indeed switched, but not because of that setting. 

In the latest builds on XDA, the regular builds do not exhibit the problem, while the extended ones do. Does that point to something else that I'm missing?

> That makes no sense

But did you actually try? It is not a sign of respect to comment without doing that. This is not quite how code review works.

**Comment by Gabriel85** [comment]
I removed the watchdog, because we don't use it. And don't need it, since the kernel is stable.
Yes, I tried! Although several months ago.. Are you telling me that changing that setting actually fixes it?

**Comment by Quallenauge** [comment]
Do we have a watchdog or not? And even the kernel might be stable, hardware issues can also cause the kernel to hang...

**Comment by Gabriel85** [comment]
Well than you can reboot it manually... However the Linux kernel already has one build in. And increasing the bite time wouldn't make sense anyways, since it defeats it's purpose.

**Comment by Quallenauge** [comment]
That's not good in case the screen is of and no one notice the crash...
Honestly, if he have an hardware watchdog, we should use them.

**Comment by Gabriel85** [comment]
Guess what the stock-ROM does in that case? I reboots into download mode! The absolute worst state it can be for any user..

**Comment by Quallenauge** [comment]
Can you please give me an onliner to provoke that behavior?

**Comment by Gabriel85** [comment]
To get into download mode? But this isn't a chat! If you wanna chat write me in Skype please..

**Comment by Quallenauge** [comment]
You're right. Please turn the watchdog on.

**Comment by vladimiroltean** [comment]
* Removed the increase of the qcom,bark-time setting for the watchdog. It was probably a debug setting that went into the public build.
* In the previous volume keys patch I missed the volume-down button configuration.
* CPR (Core Power Reduction) regulator documentation is here: https://github.com/Lenovo-YTX703-Devel/android_kernel_lenovo_msm8976/blob/lineage-15.1/Documentation/devicetree/bindings/regulator/cpr-regulator.txt. Again, I see no reason why we would change this from stock.

**Comment by Gabriel85** [comment]
I'm good with switching the keys, but I see no point in changing the voltage back now, while nobody has complained about it. There is no reason to believe that it does any good, nor can it damage anything. If somebody complains about any stability issue we still can change it. Also there is no comment or anything by Lenovo, that this is important, at all. They didn't even adjust the voltages, they just disable the scaling completely. I bet somebody changed it during development for some reason, and just forgot to set it back..
Furthermore, I can see no point in changing a decimal number into a hex one..

**Comment by vladimiroltean** [comment]
I removed the CPR regulator commit from this pull request, as it's blocking the volume keys patch from getting merged.

**Review by Gabriel85 — APPROVED** [review]

**Review by Quallenauge — APPROVED** [review]

**Pull request merged**
