### PR TITLE
DEFCONFIG: Enable support for USB Ethernet adapters

### PR DESCRIPTION
**Pull request by vladimiroltean**
Change-Id: Ic62a2a300cc88144dd4806243c93aef195408bba
Signed-off-by: Vladimir Oltean <olteanv@gmail.com>

### CODE REVIEW

**Comment by Gabriel85** [comment]
Most USB Ethernet adapters are already supported, but I'll add this to my revised defconfig.

**Comment by Quallenauge** [comment]
Revised defconfig?

**Comment by vladimiroltean** [comment]
> Most USB Ethernet adapters are already supported

Tell me the USB Ethernet adapter that you tested and you claim it works with the current branch tip, and I'll buy it to check.

**Comment by Gabriel85** [comment]
Well I found a list on the internet with the most common chipsets. And I added the modules that you told me. Or didn't I? Maybe I made a mistake, couldn't test it.

**Review by Quallenauge — APPROVED** [review]
Despite the fact I never used that on my device, it can be an enrichment for power users.
Also if the feature isn't used I think it doesn't makes noises.

**Pull request merged**
